export enum SessionDataModificationFlag {
    ACTUAL_DATE_TIME = 'ACTUAL_DATE_TIME', 
	COMPLETED_EVENT_IDS = 'COMPLETED_EVENT_IDS', 
	EVENT = 'EVENT', 
	EVENT_COMPLETION_PERCENT = 'EVENT_COMPLETION_PERCENT', 
	EVENT_TRIGGER_START_TIMES = 'EVENT_TRIGGER_START_TIMES', 
	LOCALE = 'LOCALE',
	NEWS_LINE = 'NEWS_LINE', 
	USER = 'USER',
    // USER_OF_EVENT = 'USER_OF_EVENT'
}
